version: "3"
services:
  gateway:
    build: ./gateway
    restart: always
    hostname: gateway
    env_file:
      - .env
    ports:
      - "5000:5000"
    networks:
      - backend

  user:
    build: ./user
    restart: always
    hostname: user
    env_file:
      - .env
    ports:
      - "5001:5001"
    networks:
      - backend

  room:
    build: ./room
    restart: always
    hostname: room
    env_file:
      - .env
    ports:
      - "5002:5002"
    networks:
      - backend

  booking:
    build: ./booking
    restart: always
    hostname: booking
    env_file:
      - .env
    ports:
      - "5003:5003"
    networks:
      - backend
